### ISSUE TITLE
Review msp +/- 3.5 hours implementation

### ISSUE THREAD

**Issue by jackhching** [annisjs/typical.sleep#16]
https://github.com/annisjs/typical.sleep/blob/b77eaddac6dd15a7fa60a094c26580bf6b634ab3/R/typical_sleep.R#L57-L66

Could you take another look at the implementation of the +/- 3.5 hour assumption? My understanding was that if the median_wake - median_bed <5 hours (e.g. someone whose data suggest a habitually short sleeping period), we should instead set the TSP BT and TSP WT to msp +/- 3.5 hours; as reflected in lines 64-66.

Lines 61-63 seems to also be adjusting the sleep log's BT and WT to be msp +/- 3.5, which does not seem necessary.
The specific-case to examine here is the 03/30/23 night, as only a single short sleep log was captured.

**Comment by annisjs** [comment]
Fixed in another branch 
https://github.com/annisjs/typical.sleep/pull/20
