### ISSUE TITLE
Ensure output has a way to get edge case for which assumption for accounting erratic sleep schedules was applied (i.e., MSP+-3.5 hrs).

### ISSUE THREAD

**Issue by hiralmaster** [annisjs/typical.sleep#8]
Given how erratic schedules may lead to incorrect BT/WT estimates, if the TSP BT is before TSP WT, but the time between them is <5 hrs (i.e., habitually dangerously short sleep durations), then the TSP BT and WT are set using the median MSP (e.g., BT=MSP-3.5hrs and WT=MSP+3.5hrs). Though this is a flawed assumption, there is a need to report the number of edge cases.

**Comment by annisjs** [comment]
Fixed here: https://github.com/annisjs/typical.sleep/pull/21
